apiVersion: v1
kind: ReplicationController
metadata:
  name: recrawler-node
  namespace: default
  labels:
    role: recrawler-node
    usage: prod
spec:
  replicas: 1
  selector:
    role: recrawler-node
  template:
    metadata:
      labels:
        role: recrawler-node
    spec:
      containers:
      - name: recrawler-node
        image: asia.gcr.io/sport-news-retrieval/recrawler:v1.1-rc5
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 8000
