proxy:
  build: .
  dockerfile: proxy/Dockerfile
  links:
  - solr-node
  - recrawler-node
  ports:
  - "80:80"
  - "443:443"
  volumes:
  - ./UI/:/usr/share/nginx/html/:rw
solr-node:
  build: .
  dockerfile: index/Dockerfile
  ports:
  - "8983:8983"
  volumes:
  - ./index/solr/sport/conf/:/tmp/solr/sport/conf/:rw
  - ./data/all_data.json:/opt/solr/data/all_data.json:rw
recrawler-node:
  build: .
  dockerfile: recrawler/Dockerfile
  links:
  - solr-node
  ports:
  - "8000:8000"
  volumes:
  - ./crawler/:/usr/src/app/crawler/:rw
  - ./recrawler/recrawl:/usr/src/app/recrawler/recrawler:rw
